# Generated by Django 5.2.5 on 2025-08-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_add', models.TextField()),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_pass', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.gender')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('dept_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.department')),
            ],
        ),
        migrations.CreateModel(
            name='DutyDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.employee')),
                ('job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.employee')),
                ('job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_labor', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('duty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.dutyduration')),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.employee')),
                ('job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.jobtitle')),
                ('leave_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.leave')),
            ],
        ),
    ]
