# Generated by Django 5.2.5 on 2025-08-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('adderss', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('emp_password', models.CharField(max_length=128)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.department')),
            ],
        ),
        migrations.CreateModel(
            name='Duty_Duretion',
            fields=[
                ('Duty_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.job_title')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('Leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.job_title')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_laber', models.CharField(max_length=120)),
                ('salary', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('duty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.duty_duretion')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.employee')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.job_title')),
                ('Leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.leave')),
            ],
        ),
    ]
